### ISSUE TITLE
Found the following error when running AWS Setup

### ISSUE THREAD

**Issue by cybergoof** [Resistor52/6100#26]
I don't know if this actually caused any problems or not.  

Subscribe to the AWS Config Service
./aws-setup.sh: line 189: 0: command not found
Waiting ./aws-setup.sh: line 193: [: !=: unary operator expected
Subscription succeeded

**Comment by Resistor52** [comment]
ok, looking at it now

**Comment by Resistor52** [comment]
I think that this is the issue http://tldp.org/LDP/abs/html/comparison-ops.html 
Different OS handle this differently.  Will push a fix in a minute

**Comment by Resistor52** [comment]
@cybergoof - Please try it again and if its is fixed, please close the ticket

**Comment by Resistor52** [comment]
Not Fixed yet
