### ISSUE TITLE
Should the *.json files be in .gitignore?

### ISSUE THREAD

**Issue by cybergoof** [Resistor52/6100#33]

**Comment by Resistor52** [comment]
Yes, they should be in .gitignore because they are dynamically generated.  Yours will be different than mine.  (They are generated by aws-setup.sh)

**Comment by Resistor52** [comment]
I need to have the teardown script delete them though.  I will do that now

**Comment by Resistor52** [comment]
Closed by https://github.com/Resistor52/6100/commit/db39b906769ccf792f598bbf73feb58318832775
