### ISSUE TITLE
Error getting Password

### ISSUE THREAD

**Issue by cybergoof** [Resistor52/6100#36]
Getting the following error when running setup.  It gives this error over and over for a good while, before moving on.  I have the latest copy of the software, and I ran it twice just to make sure

...............EC2 Instance post-launch configuration and status checks are complete

Waiting on the availability of the Windows Password

An error occurred (InvalidInstanceID.NotFound) when calling the GetPasswordData operation: The instance ID 'i-042979bc90cf49248' does not exist

**Comment by Resistor52** [comment]
yes, I have a fix pending.  if you look in the `generate-windowspw.sh` you can see an issue with the script that was generated.  (I used a >> instead of a >)

The temp work around is to delete all of the lines but the last two in `generate-windowspw.sh`

**Comment by cybergoof** [comment]
its not stopping me.  just making sure you were aware.
