### ISSUE TITLE
Hangup if profile's region is incorrect

### ISSUE THREAD

**Issue by cybergoof** [Resistor52/6100#5]
I had a typo for the region for my parameter.  If it is incorrect, this command would hang
`aws ec2 describe-key-pairs --profile $AWS_DEFAULT_PROFILE` 

Not sure what can be done, other than validate that the region is correct in the parameter.

**Comment by Resistor52** [comment]
Did you get the latest version of the scripts?  I am now validating the region.  See line 42 of https://github.com/Resistor52/6100/blob/master/aws-setup.sh 

To get the latest, do a git fetch then a git pull (see https://github.com/Resistor52/6100/blob/master/GitCheatsheet.md)

**Comment by cybergoof** [comment]
the validation happens at line 58?  The first aws call that requires proper config information is in line 34.  Not sure if the validation can happen earlier.

I did look online to see if there were ways to run a timeout in case it hangs, but it looks like you might need a non-standard package.

**Comment by Resistor52** [comment]
Good catch, I can change the order of these validations.  The region should be validated before line 34 and then the aws command in line 34 needs to include the specific region parameter.  I will fix tonight

**Comment by Resistor52** [comment]
Fixed. See https://github.com/Resistor52/6100/commit/40595bec0a8ca29435b208e5917fbf279a116cb9
