### ISSUE TITLE
Move user specific config info out of shell scripts

### ISSUE THREAD

**Issue by cybergoof** [Resistor52/6100#6]
If the shell script gets updated, the profile information gets overwritten.  Either move them to a config file, or, have them entered at a command prompt.

**Comment by Resistor52** [comment]
I was trying to think of how to do this and maybe there is a way to read these items out of a config file that doesn't get saved to the repository?  If you have an idea of how to do this go ahead and push the change otherwise I will take a whack at it.

**Comment by Resistor52** [comment]
Fixed. See https://github.com/Resistor52/6100/commit/40595bec0a8ca29435b208e5917fbf279a116cb9
